DROP TABLE IF EXISTS airline_tb;

DROP TABLE IF EXISTS city_tb;

DROP TABLE IF EXISTS flight_tb;

CREATE TABLE airline_tb (
  ID INT NOT NULL  AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

CREATE TABLE city_tb (
  ID INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  POPULATION INT NOT NULL
);

CREATE TABLE city_tb (
  ID INT NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  AIRLINE_ID INT NOT NULL,
  SOURCE_CITY_ID INT NOT NULL,
  DESTINATION_CITY_ID INT NOT NULL,
  DISTANCE INT NOT NULL,
  SCHEUDELE_MIN INT NOT NULL
);
